// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RadioScheduler.Utils;

#nullable disable

namespace RadioScheduler.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("RadioScheduler.Models.Accounting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("account_name");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("account_number");

                    b.Property<decimal>("Credit")
                        .HasColumnType("TEXT")
                        .HasColumnName("credit");

                    b.Property<decimal>("Debit")
                        .HasColumnType("TEXT")
                        .HasColumnName("debit");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_date");

                    b.Property<int>("VAT")
                        .HasColumnType("INTEGER")
                        .HasColumnName("v_a_t");

                    b.HasKey("Id");

                    b.ToTable("accountingdb");
                });

            modelBuilder.Entity("RadioScheduler.Models.Auth.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int?>("RoleName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.ToTable("global_role", (string)null);
                });

            modelBuilder.Entity("RadioScheduler.Models.Auth.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("zip_code");

                    b.HasKey("Id");

                    b.ToTable("global_user", (string)null);
                });

            modelBuilder.Entity("RadioScheduler.Models.Auth.UserLogin", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("LoginTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("login_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_login", (string)null);
                });

            modelBuilder.Entity("RadioScheduler.Models.Auth.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_role", (string)null);
                });

            modelBuilder.Entity("RadioScheduler.Models.ContributorPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountingId")
                        .HasColumnType("TEXT")
                        .HasColumnName("accounting_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_paid");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountingId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("contributor_payment", (string)null);
                });

            modelBuilder.Entity("RadioScheduler.Models.RadioHost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_guest");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.ToTable("global_radio_host", (string)null);
                });

            modelBuilder.Entity("RadioScheduler.Models.RadioShow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("DurationMin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_min");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("global_radio_show", (string)null);
                });

            modelBuilder.Entity("RadioScheduler.Models.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("month");

                    b.PrimitiveCollection<string>("TableauIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tableau_ids");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("global_schedule", (string)null);
                });

            modelBuilder.Entity("RadioScheduler.Models.Studio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal>("BookingPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("booking_price");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("capacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("global_studio", (string)null);
                });

            modelBuilder.Entity("RadioScheduler.Models.Tableau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("schedule_id");

                    b.HasKey("Id");

                    b.ToTable("tableau");
                });

            modelBuilder.Entity("RadioScheduler.Models.Timeslot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<Guid>("TableauId")
                        .HasColumnType("TEXT")
                        .HasColumnName("tableau_id");

                    b.HasKey("Id");

                    b.HasIndex("TableauId");

                    b.ToTable("timeslot");
                });

            modelBuilder.Entity("timeslot_host", b =>
                {
                    b.Property<Guid>("host_id")
                        .HasColumnType("TEXT")
                        .HasColumnName("host_id");

                    b.Property<Guid>("timeslot_id")
                        .HasColumnType("TEXT")
                        .HasColumnName("timeslot_id");

                    b.HasKey("host_id", "timeslot_id");

                    b.HasIndex("timeslot_id");

                    b.ToTable("timeslot_host");
                });

            modelBuilder.Entity("RadioScheduler.Models.Auth.UserLogin", b =>
                {
                    b.HasOne("RadioScheduler.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RadioScheduler.Models.Auth.UserRole", b =>
                {
                    b.HasOne("RadioScheduler.Models.Auth.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RadioScheduler.Models.Auth.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RadioScheduler.Models.ContributorPayment", b =>
                {
                    b.HasOne("RadioScheduler.Models.Accounting", "Accounting")
                        .WithOne("ContributorPayment")
                        .HasForeignKey("RadioScheduler.Models.ContributorPayment", "AccountingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RadioScheduler.Models.Auth.User", "User")
                        .WithMany("ContributorPayments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RadioScheduler.Models.Timeslot", b =>
                {
                    b.HasOne("RadioScheduler.Models.RadioShow", "RadioShow")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RadioScheduler.Models.Studio", "Studio")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RadioScheduler.Models.Tableau", null)
                        .WithMany("Timeslots")
                        .HasForeignKey("TableauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RadioShow");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("timeslot_host", b =>
                {
                    b.HasOne("RadioScheduler.Models.RadioHost", null)
                        .WithMany()
                        .HasForeignKey("host_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RadioScheduler.Models.Timeslot", null)
                        .WithMany()
                        .HasForeignKey("timeslot_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RadioScheduler.Models.Accounting", b =>
                {
                    b.Navigation("ContributorPayment")
                        .IsRequired();
                });

            modelBuilder.Entity("RadioScheduler.Models.Auth.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("RadioScheduler.Models.Auth.User", b =>
                {
                    b.Navigation("ContributorPayments");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("RadioScheduler.Models.Tableau", b =>
                {
                    b.Navigation("Timeslots");
                });
#pragma warning restore 612, 618
        }
    }
}
